all: prime point

.PHONY: prime point

prime:
	g++ primes/main.cpp -o prime -std=c++14 -Wall -Wextra -pedantic -g

point:
	g++ fixed-point/main.cpp -o point -std=c++14 -Wall -Wextra -pedantic -g

clean:
	rm -f primes point